package bo.game.event;

public enum CurrentEventEffect {
    IGNORE_1_EAGLE_ON_ALL_PLOT_ATTEMPTS,
    IGNORE_2_EAGLES_ON_ALL_PLOT_EVENTS,
    ADD_1_EAGLE_TO_ALL_PLOT_ATTEMPTS,
    MOVE_TO_NUREMBERG_SET_SUSPICION_TO_LOW,
    DISSENT_TRACK_REWARD_ALL_PLAYERS_MAY_INCREASE_MOTIVATION_BY_1
}
