package bo.game.event;

public enum EventCardEffect {
    // Stage 1
    PARADE_IN_BERLIN,
    VISIT_FROM_GOEBBELS_1,
    PARTY_RALLY_1,
    LEADERSHIP_DISPUTE,
    VISIT_FROM_HIMMLER_1,
    KRISTALLNACHT,
    BERLIN_SPEECH,

    // Stage 2
    ASSASSIN_CAUGHT,
    GESTAPO_INVESTIGATION,
    MUNICH_AGREEMENT,
    BLOMBERG_FRITSCH_AFFAIR,
    ANSCHLUSS,
    STRATEGY_SESSION_A,
    STRATEGY_SESSION_B,
    VISIT_FROM_HESS,
    GESTAPO_RAID,
    ANTISEMETIC_LAWS,
    VISIT_FROM_BORMANN_2,
    INVASION_OF_POLAND,
    NAZI_SOVIET_PACT,
    PARTY_RALLY_2,
    SUDETENLAND_OCCUPATION,
    CZECH_INVADED,

    // Stage 3
    VISIT_FROM_HITLER_3,
    BERGHOF_RETREAT_3,
    VISIT_FROM_GOERING_3,
    JEWS_TARGETED,
    LONDON_BOMBED,
    GERMANY_BOMBED,
    SEALION_POSTPONED,
    WESTERN_OFFENSIVE,
    INVASION_OF_NORWAY,
    FALL_OF_PARIS,

    // Stage 4
    VISIT_FROM_HIMMLER_4,
    WAR_CONFERENCE,
    HESS_LEAVES_GERMANY,
    VISIT_FROM_GOEBBELS_4,
    AFRIKA_KORPS,
    YUGOSLAVIA_SURRENDERS,
    PEARL_HARBOR_ATTACK,
    FALL_OF_KIEV,
    OPERATION_BARBAROSSA,
    HITLER_ASSUMES_COMMAND,

    // Stage 5
    VISIT_FROM_BORMANN_5,
    VISIT_FROM_GOERING_5,
    CASABLANCA_CONFERENCE,
    HEYDRICH_ASSASSINATED,
    BERGHOF_RETREAT_5,
    ROMMEL_DEFEATED,
    RUSSIAN_SETBACK,
    VISIT_FRONT,
    EASTERN_PUSH,
    LEBENSRAUM,

    // Stage 6
    VISIT_FROM_HITLER_6,
    SLOW_RETREAT,
    BERLIN_BOMBED,
    WARSAW_GHETTO_UPRISING,
    STALINGRAD_SURROUNDED,
    WOLFPACKS,
    SICILY_INVADED,
    FORTRESS_EUROPA,
    KURSK_RECAPTURED,

    // Stage 7
    V2_ROCKET,
    FUHRER_BUNKER,
    OPERATION_OVERLORD,
    GOTHIC_LINE,
    ROMMEL_EXECUTED,
    DOCUMENTS_LOCATED,
    FALL_OF_ROME,
    FINAL_CONSCRIPTION,
    ANZIO_LANDING
}
