package bo.game.location;

public enum LocationModifier {
    SUSPICION_MINUS_2,
    SUSPICION_MINUS_2_STAGE_2,
    SUSPICION_MINUS_2_STAGE_1,
    SUSPICION_MINUS_2_IF_ABWEHR,
    SUSPICION_MINUS_2_IF_CIVILIAN,
    SUSPICION_MINUS_2_IF_WEHRMACHT,
    SUSPICION_MINUS_2_IF_DEPUTY_PRESENT,
    SUSPICION_MINUS_2_IF_HITLER_PRESENT,
    SUSPICION_MINUS_3_MILITARY_SUPPORT_PLUS_1,
    SUSPICION_MINUS_3_DISTRIBUTED,
    SUSPICION_PLUS_1,
    MOTIVATION_PLUS_2_SUSPICION_PLUS_1
}
